version: '3'
services:
  rabbit1:
    image: "rabbitmq:3-management"
    hostname: "rabbit1"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq1"
  
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finchat
    ports:
      - 15432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 18080:8080

  goserver:
    build:
      context: "."
      dockerfile: "Dockerfile.web"
    depends_on:
      - rabbit1
      - db
    environment:
      - RABBIT_CONNECTION=amqp://rabbitmq:rabbitmq@rabbit1:5672/
      - DB_CONNECTION=host=db port=5432 user=postgres password=postgres dbname=finchat sslmode=disable
    volumes:
      - .:/usr/src/app
    ports:
      - "8001:8001"

  gobot:
    build:
      context: "."
      dockerfile: "Dockerfile.bot"
    environment:
      - RABBIT_CONNECTION=amqp://rabbitmq:rabbitmq@rabbit1:5672/
    volumes:
      - .:/usr/src/app
    depends_on:
      - rabbit1
    